typography_spectrum: 0.03806470846757293
color:
  brandStrength: 0.2407126654870808
  lightness: 0.9648547233082354
  saturation: 0.19902542349882424
  rhythmicContrast: 0.6030103208031505
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.36888266378082335
name: Tools for the Journey
navigation:
  - name: “Bright Lines Journal” now available!
    id: ff6968d4-6cad-4083-a755-20bf6c62e5f6
    type: content
title: Warrior Mystic
description: Tools and Resources to help you walk your path
